platform :ios, '10.0'

target 'MovieApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieApp
  pod 'Alamofire'
  pod 'AlamofireImage'
  pod 'RealmSwift'
  pod 'youtube-ios-player-helper'

  target 'MovieAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
